name: Build and test

# README:
#
# The semantics for running shell commands in GitHub actions is non-obvious. Please read
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
# before modifying this file. Our strategy is to rely on the built-in (unspecified) shell, and
# explicitly set the shell settings we want (with `set -eo pipefail`) at the beginning of any
# bash script. For more information on these settings, see `man bash`.
#
# GitHub Actions files can be difficult to modify with confidence, because testing changes often
# requires pushing to a branch and running CI remotely. To make this process easier, consider
# the following:
#
# 1) Use Visual Studio Code with the GitHub Actions Extension (github.vscode-github-actions).
#    This allows you to check the validity of your action schema and syntax without pushing to a
#    branch.
# 2) Use https://github.com/nektos/act to run your CI steps locally. Note this will only work with
#    steps run on Linux platforms, as `act` is implemented with Docker containers.

on:
  workflow_call:
    inputs:
      build-type:
        description: 'The build configuration type'
        default: 'debug'
        required: false
        type: string

jobs:
  build-devcontainer-linux:
    name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
    strategy:
      fail-fast: false
      matrix:
        host: [
          { type: linux, os: ubuntu-latest,
            build-options: "--build-tests -Xswiftc -enable-testing",
            test-options: "--enable-code-coverage"
          }
        ]
        # configuration: [ "debug", "release" ]

    runs-on: ${{ matrix.host.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-

    - name: Create artifact directory
      run: mkdir -p /home/runner/work/hylo-lsp/hylo-lsp/artifacts

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Test
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/koliyo/hylo-lsp-swift-devcontainer
        cacheFrom: ghcr.io/koliyo/hylo-lsp-swift-devcontainer
        runCmd: |
          set -eo pipefail
          swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
          BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
          echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
          cp $BUILD_DIR/hylo-lsp-client $BUILD_DIR/hylo-lsp-server /artifacts/
          # swift test -c ${{ inputs.build-type }} ${{ matrix.host.test-options }} |
          #   tee testoutput.txt && (
          #     (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
          #     (echo "error: generated tests failed to run; see
          #     https://github.com/apple/swift-package-manager/issues/6595" && false) )

    # - name: Check code coverage
    #   uses: mattpolzin/swift-codecov-action@0.7.3
    #   with:
    #     SORT_ORDER: +cov
    #     MINIMUM_COVERAGE: 84
    #     CODECOV_JSON: .build/${{ inputs.build-type }}/codecov/*.json


    - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
      uses: actions/upload-artifact@v3
      with:
        name: hylo-lsp-artifacts-linux
        path: |
          artifacts/hylo-lsp-client
          artifacts/hylo-lsp-server

  build-native-macos:
    name: "Build and test: ${{ matrix.host.os }}/${{ inputs.build-type }}"
    strategy:
      fail-fast: false
      matrix:
        host: [
          {
            type: macos, os: macos-13,
            build-options: "--build-tests -Xswiftc -enable-testing",
            # No coverage support on MacOS
            test-options: ""
          }
        ]
        swift: [
          { version: "5.9" }
        ]
        # configuration: [ $BUILD_TYPE ]
        # configuration: [ "debug", "release" ]

    runs-on: ${{ matrix.host.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Setup swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift.version }}

    - run: swift --version

    - name: Build (${{ inputs.build-type }})
      id: build
      run: |
        set -eo pipefail
        export PKG_CONFIG_PATH=$PWD/hylo
        swift build -c ${{ inputs.build-type }} ${{ matrix.host.build-options }}
        BUILD_DIR=$(swift build -c ${{ inputs.build-type }} --show-bin-path)
        echo "BUILD_DIR=$BUILD_DIR" >> $GITHUB_ENV
    # - name: Test (${{ inputs.build-type }})
    #   run: |
    #     set -eo pipefail
    #     export PKG_CONFIG_PATH=$PWD/hylo
    #     swift test -c ${{ inputs.build-type }} ${{ matrix.host.test-options }} |
    #       tee testoutput.txt && (
    #         (grep -q "[.']EndToEndTests[/. ]test_" testoutput.txt && grep -q "[.']HyloTests[/. ]test_" testoutput.txt) ||
    #         (echo "error: generated tests failed to run; see
    #         https://github.com/apple/swift-package-manager/issues/6595" && false) )

    - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
      uses: actions/upload-artifact@v3
      with:
        name: hylo-lsp-artifacts-mac
        path: |
          ${{ env.BUILD_DIR }}/hylo-lsp-client
          ${{ env.BUILD_DIR }}/hylo-lsp-server

  build-native-windows:
    name: "Build and test: windows-latest/${{ inputs.build-type }}"
    # strategy:
    #   fail-fast: false
    runs-on: windows-latest
    steps:
    - name: Setup swift
      uses: compnerd/gha-setup-swift@main
      with:
        branch: swift-5.9-release
        tag: 5.9-RELEASE

    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Swift version
      run: swift --version

    - name: Build and copy support library
      run: |
        clang -c ./Library/Hylo/LibC.c -o HyloLibC.lib
        xcopy HyloLibC.lib c:\program" "files\microsoft" "visual" "studio\2022\enterprise\vc\tools\msvc\${{ env.VCToolsVersion }}\lib\x64\
      working-directory: hylo

    - name: Build (Release)
      id: build
      # continue-on-error: true
      run: |
        $BUILD_DIR = swift build -c ${{ inputs.build-type }} --show-bin-path
        echo BUILD_DIR=$BUILD_DIR
        echo BUILD_DIR=$BUILD_DIR >> $env:GITHUB_ENV
        swift build -c ${{ inputs.build-type }}

    # - name: Copy artifacts
    #   run: |
    #     $BUILD_DIR = swift build -c ${{ inputs.build-type }} --show-bin-path
    #     xcopy $BUILD_DIR artifacts /I

    - name: Upload Hylo LSP artifacts (${{ inputs.build-type }})
      uses: actions/upload-artifact@v3
      with:
        name: hylo-lsp-artifacts-windows
        path: |
          ${{ env.BUILD_DIR }}/hylo-lsp-client.exe
          ${{ env.BUILD_DIR }}/hylo-lsp-server.exe
        # artifacts/hylo-lsp-client.exe
        # artifacts/hylo-lsp-server.exe

    # - name: Retry on failure
    #   continue-on-error: false
    #   if: steps.build.outcome != 'success'
    #   run: swift build -v -c release

