name: Build and test

# README:
#
# The semantics for running shell commands in GitHub actions is non-obvious. Please read
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
# before modifying this file. Our strategy is to rely on the built-in (unspecified) shell, and
# explicitly set the shell settings we want (with `set -eo pipefail`) at the beginning of any
# bash script. For more information on these settings, see `man bash`.
#
# GitHub Actions files can be difficult to modify with confidence, because testing changes often
# requires pushing to a branch and running CI remotely. To make this process easier, consider
# the following:
#
# 1) Use Visual Studio Code with the GitHub Actions Extension (github.vscode-github-actions).
#    This allows you to check the validity of your action schema and syntax without pushing to a
#    branch.
# 2) Use https://github.com/nektos/act to run your CI steps locally. Note this will only work with
#    steps run on Linux platforms, as `act` is implemented with Docker containers.

on:
  workflow_call:
    inputs:
      build-type:
        description: 'The build configuration type'
        default: 'debug'
        required: false
        type: string

jobs:

  build-native-macos-latest:
    runs-on: macos-latest
    steps:
    - run: uname -a

  build-native-macos-13:
    runs-on: macos-13
    steps:
    - run: uname -a

  build-native-macos-13-xl:
    runs-on: macos-13-xl
    steps:
    - run: uname -a
