name: Publish release version

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
  publish-release:
    needs: [build]
    strategy:
      fail-fast: false

      matrix:
        host: [
          {
            type: macos, os: macos-13,
            build-options: "--build-tests -Xswiftc -enable-testing",
            # No coverage support on MacOS
            test-options: "-v"
          }
        ]

    runs-on: ${{ matrix.host.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download Hylo LSP artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-and-test.yml
        name: hylo-lsp-artifacts-mac

    - name: Display structure of downloaded files
      run: ls -R

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          LICENSE
          hylo-lsp-artifacts-mac/*
