name: Publish release version

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    name: Build and test
    uses: ./.github/workflows/build-and-test-template.yml
    with:
      build-type: release
  publish-release:
    name: Publish release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Download hylo-lsp-artifacts-mac
      uses: actions/download-artifact@v3
      with:
        name: hylo-lsp-artifacts-mac
        path: hylo-lsp-mac

    - name: Package Hylo release artifacts
      run: |
        set -eo pipefail
        cp -Rp hylo/Library/Hylo hylo-stdlib
        ls -l hylo-lsp-mac/
        chmod +x hylo-lsp-mac/*
        tar -zcvf hylo-stdlib.tar.gz hylo-stdlib
        tar -zcvf hylo-lsp-mac.tar.gz hylo-lsp-mac

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          LICENSE
          hylo-lsp-mac.tar.gz
          hylo-stdlib.tar.gz
