name: Publish release version

on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    uses: ./.github/workflows/build-and-test.yml
  publish-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Download Hylo LSP artifact-mac
      id: download-artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-and-test.yml
        name: hylo-lsp-artifacts-mac
        path: hylo-lsp-mac

    # - name: Download Hylo LSP artifact-common
    #   id: download-artifact
    #   uses: dawidd6/action-download-artifact@v2
    #   with:
    #     workflow: build-and-test.yml
    #     name: hylo-lsp-artifacts-common
    #     path: hylo-lsp-artifacts-common

    - name: Package Hylo stdlib
      run: |
        set -eo pipefail
        cp -Rp hylo/Library/Hylo hylo-stdlib
        chmod +x hylo-lsp-mac/*
        tar -zcvf hylo-stdlib.tar.gz hylo-stdlib
        tar -zcvf hylo-lsp-mac.tar.gz hylo-lsp-mac

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          LICENSE
          hylo-lsp-mac.tar.gz
          hylo-stdlib.tar.gz
